name: FREE FIRE RDP

on:
  workflow_dispatch:
    inputs:
      code:
        description: Paste Chrome Remote Desktop Code
        required: true

jobs:
  build:
    name: Free Fire Ripper Lab Running
    runs-on: windows-latest
    timeout-minutes: 360

    steps:
    - name: Checkout RDP-FILE-SAVE repo
      uses: actions/checkout@v3
      with:
        repository: gringomodz/RDP-FILE-SAVE
        token: ${{ secrets.GH_TOKEN }}
        path: savefiles

    - name: Restore previous data
      run: |
        Copy-Item -Path savefiles\* -Destination "C:\Users\${Env:USERNAME}\Documents" -Recurse -Force -ErrorAction SilentlyContinue

    - name: Downloading And Installing Free Fire And Tools
      continue-on-error: true
      run: |
        & { Set-NetFirewallProfile -Profile Domain,Public,Private -Enabled False }

        function Install-PackageWithRetry {
            param ([string]$packageName)
            $maxRetries = 3
            $retryCount = 0
            $success = $false
            while (-not $success -and $retryCount -lt $maxRetries) {
                try {
                    choco install $packageName -y
                    $success = $true
                } catch {
                    Start-Sleep -Seconds 10
                    $retryCount++
                }
            }
            if (-not $success) {
                if ($packageName -eq 'googlechrome') {
                    Invoke-WebRequest -Uri "https://dl.google.com/chrome/install/latest/chrome_installer.exe" -OutFile "chrome_installer.exe"
                    Start-Process "chrome_installer.exe" -ArgumentList "/silent", "/install" -Wait
                } elseif ($packageName -eq 'chrome-remote-desktop-host') {
                    Invoke-WebRequest -Uri "https://dl.google.com/edgedl/chrome-remote-desktop/chromeremotedesktophost.msi" -OutFile "chromeremotedesktophost.msi"
                    Start-Process "msiexec.exe" -ArgumentList "/i", "chromeremotedesktophost.msi", "/quiet", "/qn" -Wait
                }
            }
        }

        Install-PackageWithRetry -packageName "chrome-remote-desktop-host"
        Install-PackageWithRetry -packageName "googlechrome"

        cd C:\Users\$Env:USERNAME\Documents
        Invoke-WebRequest -Uri "https://drive.usercontent.google.com/download?id=11EUFz6hufNT1g56-CmOJw9_KxMERZxhe&export=download&authuser=0&confirm=t" -OutFile ffripper.zip
        7z x ffripper.zip -y

        $chromeRemoteDesktopPath = "${Env:PROGRAMFILES(X86)}\Google\Chrome Remote Desktop\CurrentVersion\remoting_start_host.exe"
        if (Test-Path $chromeRemoteDesktopPath) {
            & $chromeRemoteDesktopPath
        }

        $noesisPath = "C:\Users\$Env:USERNAME\Documents\noesis\Noesis64.exe"
        if (Test-Path $noesisPath) {
            Start-Process $noesisPath
        }

        $ninjaripperPath = "C:\Users\$Env:USERNAME\Documents\ninjaripper\x86\ninjaripper.exe"
        if (Test-Path $ninjaripperPath) {
            Start-Process $ninjaripperPath
        }

        New-Item -ItemType SymbolicLink -Target "C:\Users\$Env:USERNAME\Documents\FenixGaga\Engine\ProjectTitan.exe" -Path "C:\Users\$Env:USERNAME\Desktop\Free Fire.lnk"
        New-Item -ItemType SymbolicLink -Target "C:\Users\$Env:USERNAME\Documents\ninjaripper\x86\NinjaRipper.exe" -Path "C:\Users\$Env:USERNAME\Desktop\Ninjaripper.lnk"
        New-Item -ItemType SymbolicLink -Target "C:\Users\$Env:USERNAME\Documents\noesis\Noesis64.exe" -Path "C:\Users\$Env:USERNAME\Desktop\Noesis.lnk"

    - name: Starting Remote Desktop
      continue-on-error: true
      run: |
        ${{ inputs.code }} -pin=123456

    - name: Keep RDP Alive
      run: |
        $i = 360999
        do {
            Write-Host "Still running: $i"
            Sleep 60
            $i--
        } while ($i -gt 0)

    - name: Save working data back to repo
      run: |
        cd C:\Users\${Env:USERNAME}\Documents
        git config --global user.email "rdp@github.com"
        git config --global user.name "GitHub RDP"
        Copy-Item * "${{ github.workspace }}\savefiles" -Recurse -Force
        cd "${{ github.workspace }}\savefiles"
        git add .
        git commit -m "Auto backup after RDP session"
        git push
